version: "3.9"
services:
  chartmuseum:
    image: ghcr.io/helm/chartmuseum:v0.14.0
    container_name: chartmuseum
    restart: always
    ports:
      - 8085:8080
    env_file:
      - DEBUG=1
      - STORAGE=local
      - STORAGE_LOCAL_ROOTDIR=/charts
    volumes:
      - ./charts:/charts
    command: --port=8080 --storage="local" --storage-local-rootdir=/charts ghcr.io/helm/chartmuseum:v0.14.0
