version: "3.9"
services:
  helm-repository:
    image: ghcr.io/helm/chartmuseum:v0.14.0
    restart: always
    ports:
      - "8085:8080"
    environment:
      - DEBUG=1
      - STORAGE=local
      - STORAGE_LOCAL_ROOTDIR=/charts
    volumes:
      - ./charts:/charts
    command: --port=8080 --storage="local" --storage-local-rootdir=/charts ghcr.io/helm/chartmuseum:v0.14.0
  docker-registry:
    image: registry:2
    restart: always
    ports:
      - "5001:5000"
    volumes:
      - ./registry:/var/lib/registry